// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPassword(arg1:main.PasswordGenerated):Promise<string>;

export function ListPasswords(arg1:number,arg2:number):Promise<main.ListPasswords>;

export function RemovePassword(arg1:number):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;
