// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPassword(arg1) {
  return window['go']['main']['App']['AddPassword'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListPasswords(arg1, arg2) {
  return window['go']['main']['App']['ListPasswords'](arg1, arg2);
}

export function RemovePassword(arg1) {
  return window['go']['main']['App']['RemovePassword'](arg1);
}

export function ShowInfo(arg1, arg2) {
  return window['go']['main']['App']['ShowInfo'](arg1, arg2);
}
