name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: TinyPasswordManager, platform: linux/amd64, os: ubuntu-latest},
          {name: TinyPasswordManager, platform: windows/amd64, os: windows-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build 
          path: |
            */bin/
            *\bin\*
      - uses: softprops/action-gh-release@v1     
        with:
          files: |
            */bin/*   